version: '3'
services:
  web:
    image: iomirea
    network_mode: host
    ports:
      - 8080
    volumes:
      - ./:/code/
    environment:
      - DATACENTER=0
      - WORKER=0
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/upstreams:/etc/nginx/upstreams
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/sites-available:/etc/nginx/sites-available
      - /etc/letsencrypt:/etc/letsencrypt
      - ./iomirea/static:/www/static
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
     - web
    network_mode: host
