version: '3'

services:
  registrator:
    image: gliderlabs/registrator
    command: "consul://${MYHOST}:8500"
    container_name: registrator
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./iomirea/static:/www/static
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    network_mode: host
