version: '3'
services:
  web:
    image: web
    build: .
    command: python iomirea/app.py
    network_mode: host
    ports:
      - 8080
    volumes:
      - ./:/code/
    depends_on:
      - migration
    restart: always
    deploy:
      restart_policy:
        condition: always
        delay: 5s
  migration:
    image: web
    command: python migrations/migrate.py
    network_mode: host
    volumes:
      - ./:/code/
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/sites-available:/etc/nginx/sites-available
      - /etc/letsencrypt:/etc/letsencrypt
      - ./iomirea/static:/www/static
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
     - web
    network_mode: host
